"""Export the exact text-expansion system prompt for human review."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PROTOTYPE = ROOT / "prototype"
sys.path.insert(0, str(PROTOTYPE))

from prompt_engine import build_text_expand_system_prompt  # noqa: E402


DEFAULT_OUTPUT = (
    PROTOTYPE / "prompts" / "compiled" / "text_expand_anima.md"
)


def export_prompt(output: Path = DEFAULT_OUTPUT) -> Path:
    prompt = build_text_expand_system_prompt("anima")
    header = (
        "<!-- Generated by scripts/export_text_expand_prompt.py. -->\n"
        "<!-- This is the exact system message sent to the text LLM. -->\n\n"
    )
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(header + prompt + "\n", encoding="utf-8")
    return output


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    print(export_prompt(args.output.resolve()))


if __name__ == "__main__":
    main()
