(function (root) {
  const referenceEntries = [
    {
      id: "rain-city",
      title: "雨夜霓虹",
      image: "assets/rain-city.png",
      category: "城市氛围",
      model: "Anima",
      tags: ["雨景", "霓虹", "全身", "夜景"],
      promptEn:
        "1girl, adult woman, solo, long silver hair, transparent umbrella, standing on a neon-lit street in heavy rain, reflective pavement, cyan and coral signs, cinematic framing, rim lighting, highly detailed",
      promptZh:
        "一位银色长发的成年女性独自撑着透明雨伞，站在大雨中的霓虹街道，湿润路面反射青色与珊瑚色灯光，电影感构图与轮廓光，细节丰富。",
      negativeEn:
        "low quality, blurry, malformed hands, extra fingers, text, watermark",
      negativeZh: "低质量、模糊、手部畸形、多余手指、文字、水印。",
    },
    {
      id: "green-library",
      title: "玻璃温室图书馆",
      image: "assets/green-library.png",
      category: "室内场景",
      model: "WAI-ANIMA",
      tags: ["植物", "图书馆", "暖光", "安静"],
      promptEn:
        "1woman, adult archivist, botanical library beneath a glass roof, warm afternoon sunlight, climbing plants, floating dust, bookshelves, contemplative expression, painterly anime illustration",
      promptZh:
        "一位成年档案管理员身处玻璃屋顶下的植物图书馆，午后暖光穿过攀爬植物与漂浮尘埃，书架环绕，神情安静沉思，绘画感动漫插画。",
      negativeEn: "flat lighting, empty shelves, low detail, text, watermark",
      negativeZh: "平淡光线、空书架、低细节、文字、水印。",
    },
    {
      id: "rooftop-pilot",
      title: "蓝调屋顶驾驶员",
      image: "assets/rooftop-pilot.png",
      category: "科幻人物",
      model: "Anima",
      tags: ["屋顶", "蓝调时刻", "科幻", "动势"],
      promptEn:
        "1woman, adult red-haired pilot, high rooftop at blue hour, wind-blown jacket, distant futuristic transit lines, diagonal city perspective, restrained amber lights, focused expression, cinematic anime concept art",
      promptZh:
        "一位红发成年女性驾驶员站在蓝调时刻的高楼屋顶，外套被风吹起，远处是未来交通线与城市灯光，斜向透视，克制的琥珀色点光，神情专注。",
      negativeEn:
        "daylight, static pose, empty background, low detail, logo, watermark",
      negativeZh: "白昼、僵硬姿势、空背景、低细节、标志、水印。",
    },
  ];

  const promptBlocks = [
    {
      id: "quality",
      label: "质量与元数据",
      hint: "质量标签、年代和整体审美",
      weight: 100,
      locked: false,
      en: "masterpiece, best quality, amazing quality, highly detailed, newest, very aesthetic",
      zh: "杰作、最佳质量、惊艳质量、高细节、较新审美、视觉精致。",
      source: "模型规则",
      confidence: 100,
    },
    {
      id: "artist",
      label: "画师与风格",
      hint: "Anima 画师标签与视觉语言",
      weight: 85,
      locked: false,
      en: "@mika pikazo, clean anime linework, polished digital illustration",
      zh: "@mika pikazo，干净动漫线稿，精致数字插画。",
      source: "画师库",
      confidence: 88,
    },
    {
      id: "subject",
      label: "主体与角色",
      hint: "人数、身份和基础外观",
      weight: 100,
      locked: true,
      en: "1girl, adult woman, solo, long silver hair, calm focused expression",
      zh: "一位成年女性，单人，银色长发，神情平静而专注。",
      source: "用户输入",
      confidence: 100,
    },
    {
      id: "appearance",
      label: "外貌",
      hint: "发型、面部、体态和可见身体特征",
      weight: 90,
      locked: false,
      en: "long silver hair, wet hair strands, clear facial features",
      zh: "银色长发、被雨水打湿的发丝、清晰的面部特征。",
      source: "Florence",
      confidence: 84,
    },
    {
      id: "outfit",
      label: "服装与配饰",
      hint: "服装、材质、鞋履、首饰和随身配件",
      weight: 90,
      locked: false,
      en: "dark raincoat, layered streetwear, weatherproof boots",
      zh: "深色雨衣、层叠街头服饰、防水短靴。",
      source: "Florence",
      confidence: 84,
    },
    {
      id: "expression",
      label: "表情与视线",
      hint: "面部表情、眼神方向和情绪的可见表现",
      weight: 80,
      locked: false,
      en: "calm focused expression, looking across the street",
      zh: "平静而专注的表情，望向街道另一侧。",
      source: "QwenVL",
      confidence: 78,
    },
    {
      id: "pose",
      label: "动作与姿态",
      hint: "姿势、肢体动作、朝向和重心",
      weight: 80,
      locked: false,
      en: "standing in the rain, weight shifted slightly onto one leg",
      zh: "站在雨中，身体重心略微移向一侧腿部。",
      source: "QwenVL",
      confidence: 78,
    },
    {
      id: "interaction",
      label: "互动",
      hint: "角色之间或角色与物体之间的接触和关系",
      weight: 80,
      locked: false,
      en: "one hand holding a transparent umbrella above her head",
      zh: "一只手将透明雨伞撑在头顶。",
      source: "QwenVL",
      confidence: 78,
    },
    {
      id: "scene",
      label: "场景",
      hint: "环境、空间关系和叙事信息",
      weight: 95,
      locked: false,
      en: "A rain-soaked neon street at night, crowded signs reflecting across the pavement while distant traffic dissolves into mist.",
      zh: "雨夜霓虹街道，密集灯牌倒映在湿润路面上，远处车流消失在薄雾中。",
      source: "Florence + LLM",
      confidence: 91,
    },
    {
      id: "effects",
      label: "特效与道具",
      hint: "雨滴、雾气、粒子和道具",
      weight: 72,
      locked: false,
      en: "heavy rain, water droplets, road reflections, light mist, subtle lens bloom",
      zh: "大雨、水滴、路面倒影、淡雾、轻微镜头辉光。",
      source: "WD14 + Florence",
      confidence: 86,
    },
    {
      id: "composition",
      label: "构图与镜头",
      hint: "景别、视角、透视和视觉重点",
      weight: 90,
      locked: false,
      en: "full body, street-level camera, cinematic framing, strong leading lines, layered depth",
      zh: "全身景别、街道高度镜头、电影感构图、明显引导线、层次景深。",
      source: "QwenVL",
      confidence: 81,
    },
    {
      id: "lighting",
      label: "光影与氛围",
      hint: "光源、色彩和情绪",
      weight: 92,
      locked: false,
      en: "cyan and coral neon, rim lighting, cool ambient light, quiet nocturnal mood",
      zh: "青色与珊瑚色霓虹、轮廓光、冷色环境光、安静夜间氛围。",
      source: "Florence + LLM",
      confidence: 89,
    },
    {
      id: "negative",
      label: "负面提示词",
      hint: "排除不希望出现的内容",
      weight: 100,
      locked: false,
      en: "worst quality, low quality, blurry, malformed hands, extra fingers, bad anatomy, text, watermark",
      zh: "最差质量、低质量、模糊、手部畸形、多余手指、错误人体结构、文字、水印。",
      source: "模型规则",
      confidence: 100,
    },
  ];

  const analyzers = {
    wd14: {
      id: "wd14",
      name: "WD14 Tagger",
      detail: "未找到本地模型",
      selected: false,
      available: false,
      status: "unavailable",
      device: "CPU / GPU",
      speed: "快速",
      raw: "",
    },
    florence: {
      id: "florence",
      name: "Florence PromptGen",
      detail: "已安装 · 真实本地识图",
      selected: true,
      available: true,
      status: "idle",
      device: "CPU",
      speed: "中等",
      raw: "",
    },
    joycaption: {
      id: "joycaption",
      name: "JoyCaption",
      detail: "尚未接入独立运行",
      selected: false,
      available: false,
      status: "unavailable",
      device: "GPU",
      speed: "较慢",
      raw: "",
    },
    qwenvl: {
      id: "qwenvl",
      name: "QwenVL",
      detail: "尚未接入独立运行",
      selected: false,
      available: false,
      status: "unavailable",
      device: "GPU",
      speed: "较慢",
      raw: "",
    },
    external: {
      id: "external",
      name: "外部视觉 API",
      detail: "尚未配置",
      selected: false,
      available: false,
      status: "unavailable",
      device: "Cloud",
      speed: "网络",
      raw: "",
    },
  };

  const quickPicks = {
    characters: [
      {
        id: "silver-runner",
        type: "characters",
        name: "银发雨夜旅人",
        meta: "成年女性 / 城市",
        targetBlock: "subject",
        en: "1girl, adult woman, solo, long silver hair, calm focused expression",
        zh: "一位成年女性，单人，银色长发，神情平静而专注。",
      },
      {
        id: "red-pilot",
        type: "characters",
        name: "红发高空驾驶员",
        meta: "成年女性 / 科幻",
        targetBlock: "subject",
        en: "1woman, adult red-haired pilot, athletic build, focused expression",
        zh: "一位红发成年女性驾驶员，体态利落，神情专注。",
      },
      {
        id: "archive-keeper",
        type: "characters",
        name: "温室档案管理员",
        meta: "成年女性 / 奇幻",
        targetBlock: "subject",
        en: "1woman, adult botanical archivist, elegant glasses, contemplative expression",
        zh: "一位成年植物档案管理员，佩戴精致眼镜，神情沉思。",
      },
    ],
    artists: [
      {
        id: "mika-pikazo",
        type: "artists",
        name: "@mika pikazo",
        meta: "高饱和 / 平面设计感",
        targetBlock: "artist",
        en: "@mika pikazo, vivid graphic color design",
        zh: "@mika pikazo，高饱和平面色彩设计。",
      },
      {
        id: "lack",
        type: "artists",
        name: "@lack",
        meta: "幻想角色 / 光影细腻",
        targetBlock: "artist",
        en: "@lack, detailed fantasy character illustration",
        zh: "@lack，细腻幻想角色插画。",
      },
      {
        id: "toi8",
        type: "artists",
        name: "@toi8",
        meta: "清爽线稿 / 柔和色彩",
        targetBlock: "artist",
        en: "@toi8, clean linework, soft color palette",
        zh: "@toi8，清爽线稿与柔和配色。",
      },
    ],
    snippets: [],
  };

  const promptTagDictionary = [
    "1girl", "1boy", "1woman", "1man", "2girls", "multiple girls", "solo",
    "long hair", "short hair", "twintails", "twin braids", "ponytail",
    "side ponytail", "ahoge", "bangs", "blunt bangs", "hair over one eye",
    "silver hair", "black hair", "blonde hair", "brown hair", "pink hair",
    "blue hair", "red hair", "white hair", "aqua hair", "gradient hair",
    "blue eyes", "red eyes", "green eyes", "golden eyes", "heterochromia",
    "closed eyes", "half-closed eyes", "looking at viewer", "looking away",
    "looking back", "smile", "gentle smile", "serious expression",
    "contemplative expression", "focused expression", "blush", "open mouth",
    "school uniform", "sailor collar", "serafuku", "pleated skirt",
    "long dress", "white dress", "china dress", "hanfu", "kimono", "yukata",
    "off-shoulder dress", "detached sleeves", "wide sleeves", "thighhighs",
    "gloves", "elbow gloves", "hair ornament", "hair ribbon",
    "hairclip", "jewelry", "earrings", "necklace", "armor", "leg armor",
    "mechanical arm", "military uniform", "hoodie", "jacket", "trench coat",
    "scarf", "cape", "witch hat", "beret", "glasses", "sunglasses",
    "standing", "sitting", "kneeling", "crouching", "lying", "walking",
    "running", "floating", "flying", "leaning forward", "arms behind back",
    "hands in pockets", "hand on own chest", "outstretched arm", "waving",
    "holding umbrella", "holding sword", "holding book", "holding cup",
    "head tilt", "dynamic pose", "action pose", "from behind",
    "from above", "from below", "from side", "close-up", "portrait",
    "upper body", "full body", "cowboy shot", "wide shot", "dutch angle",
    "depth of field", "blurry background", "bokeh", "foreshortening",
    "cinematic framing", "cinematic lighting", "dramatic lighting",
    "rim lighting", "backlighting", "soft lighting", "warm lighting",
    "volumetric lighting", "god rays", "sunlight", "moonlight",
    "golden hour", "blue hour", "neon lights", "lens flare", "sparkle",
    "light particles", "floating dust", "glowing", "silhouette",
    "outdoors", "indoors", "cityscape", "city lights", "night city",
    "rainy day", "heavy rain", "rain", "snow", "snowing", "cherry blossoms",
    "falling petals", "autumn leaves", "forest", "bamboo forest", "mountain",
    "waterfall", "river", "lake", "ocean", "beach", "sky", "cloudy sky",
    "starry sky", "night sky", "sunset", "sunrise", "aurora", "milky way",
    "classroom", "library", "cafe", "shrine", "torii", "temple",
    "ancient chinese architecture", "palace", "castle", "ruins",
    "rooftop", "balcony", "alley", "street", "crosswalk", "train interior",
    "greenhouse", "flower field", "garden", "courtyard",
    "masterpiece", "best quality", "highly detailed", "intricate details",
    "ultra detailed", "sharp focus", "professional finish",
    "painterly style", "watercolor", "oil painting", "ink wash painting",
    "pixel art", "cel shading", "flat color", "pastel colors",
    "vibrant colors", "muted colors", "monochrome", "limited palette",
    "anime concept art", "illustration", "key visual", "official art",
    "wind", "wind lift", "floating hair", "fluttering clothes",
    "reflection", "wet", "water drops", "steam", "fog", "mist", "smoke",
    "fire", "embers", "lightning", "petals on water", "ripples"
  ];

  const data = {
    referenceEntries,
    promptTagDictionary,
    promptBlocks,
    analyzers,
    quickPicks,
  };

  root.PROMPT_STUDIO_DATA = data;
  if (typeof module !== "undefined" && module.exports) {
    module.exports = data;
  }
})(typeof globalThis !== "undefined" ? globalThis : this);
